# Fetching the latest node image on apline linux
FROM node:alpine

# Declaring env
ENV NODE_ENV $NODE_ENV

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./package.json ./
RUN npm install

# Copying all the files in our project
COPY . .

# Building our application
# RUN npm run build
RUN npm start
